### ISSUE TITLE
Functionality TODO List

### ISSUE THREAD

**Issue by Hammershlag** [Hammershlag/MerchStore#1]
- [x] Registration page with more info
- [x] Store images as Blobs in database
- [x] Add user display from home 
- [x] Add ading items with one of the categories from db
- [x] Add Searching items
- [x] Add categories
- [x] Add gender to user 
- [x] Display user with image
- [x] Display user without image
- [x] Display item full page
- [x] Display item box template
- [x] Proper interfaces
- [x] Item cart db
- [x] Update user page
- [x] Logout
- [x] User profile redirect from home
- [x] Scale down user profile pictures
- [x] Add birth date to user
- [x] Add admin role functionality
- [x] Cart functionality
- [x] Item  sorting like in cart
- [x] Terms and conditions when registering 
- [x] Redirect to previous page after login
- [x] Divide viewing items and cart into pages
- [x] Custom error displaying
- [x] Add login by email
