### ISSUE TITLE
Functionality TODO List 2

### ISSUE THREAD

**Issue by Hammershlag** [Hammershlag/MerchStore#2]
- [x] Owner that can add new users and set their role. Has all admin privillages
- [x] Item reviews only if item was ever bought by user (can be also returned)
- [x] Add checkout
- [x] Database orders, order_items, invoices tables new structure
- [x] Add discount for specific item
- [x] User bought items record for reviews (idea???)
- [x] Add orders
- [x] Successful login popup script
- [x] Invoice to pdf (json at start)
- [x] Add banners to display ads of products
- [x] Save item price in checkout - was implemented. I quess my IQ was low when adding this :)
- [x] Update items
- [x] Documentation
- [x] User can go to item view straight from order with this item
- [ ] Database backup and restore automation
- [ ] Add internationalization
- [x] Add support
- [x] Add contact
- [x] Add redirects to everything in footer 
- [ ] Contenarize app
- [x] Bestsellers
- [x] Product history with cookies
- [ ] Login via Google
- [ ] Add real products to database
- [x] Add item display while searching in search box
- [x] Add multiple currencies 
- [ ] Add item tags/attributes (for example if its in kg or liters)
- [x] Add proper indexes to database tables
- [x] Add wishlist
