### ISSUE TITLE
UI TODO List

### ISSUE THREAD

**Issue by Hammershlag** [Hammershlag/MerchStore#3]
- [ ]  Pretty UI
- [ ] Move all styles to separate styles.css
- [x] Navigation bar with item search
- [x] Footer
- [x] Base html page template - inside templates/File Templates/Custom
- [x] Header
- [ ] Home page
